# Generated by Django 4.2.3 on 2023-08-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
