# Generated by Django 4.2.3 on 2023-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_couponcode_course_alter_couponcode_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
